-- Add concurrency-safe slot locks for booking confirmation.
-- Run this in Supabase SQL Editor before deploying the new booking + waitlist flow.

CREATE EXTENSION IF NOT EXISTS btree_gist;

/* -------------------------------------------------------------------------- */
/* 1) BOOKINGS: deterministic slot keys + overlap prevention for active rows. */
/* -------------------------------------------------------------------------- */

ALTER TABLE bookings
    ADD COLUMN IF NOT EXISTS slot_key TEXT;

ALTER TABLE bookings
    ADD COLUMN IF NOT EXISTS notes TEXT;

ALTER TABLE bookings
    ADD COLUMN IF NOT EXISTS slot_range tstzrange;

CREATE OR REPLACE FUNCTION bookings_set_slot_fields()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.workspace_id IS NOT NULL AND NEW.start_time IS NOT NULL AND NEW.end_time IS NOT NULL THEN
        NEW.slot_key := CONCAT(NEW.workspace_id::text, ':', NEW.start_time::text, ':', NEW.end_time::text);
        NEW.slot_range := tstzrange(NEW.start_time, NEW.end_time, '[)');
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_bookings_set_slot_fields ON bookings;

CREATE TRIGGER trg_bookings_set_slot_fields
BEFORE INSERT OR UPDATE OF workspace_id, start_time, end_time
ON bookings
FOR EACH ROW
EXECUTE FUNCTION bookings_set_slot_fields();

UPDATE bookings
SET
    slot_key = CONCAT(workspace_id::text, ':', start_time::text, ':', end_time::text),
    slot_range = tstzrange(start_time, end_time, '[)')
WHERE workspace_id IS NOT NULL
  AND start_time IS NOT NULL
  AND end_time IS NOT NULL
  AND (slot_key IS NULL OR slot_range IS NULL);

WITH ranked_active_slots AS (
    SELECT
        id,
        ROW_NUMBER() OVER (
            PARTITION BY slot_key
            ORDER BY
                CASE status
                    WHEN 'checked_in' THEN 0
                    WHEN 'confirmed' THEN 1
                    ELSE 2
                END,
                created_at DESC NULLS LAST,
                id DESC
        ) AS row_num
    FROM bookings
    WHERE slot_key IS NOT NULL
      AND status IN ('confirmed', 'checked_in')
), duplicated_active_rows AS (
    SELECT id
    FROM ranked_active_slots
    WHERE row_num > 1
)
UPDATE bookings b
SET
    status = 'cancelled',
    notes = CONCAT_WS(
        E'\n',
        NULLIF(b.notes, ''),
        CONCAT('Auto-cancelled duplicate active slot on ', NOW()::text)
    )
FROM duplicated_active_rows d
WHERE b.id = d.id;

DROP INDEX IF EXISTS idx_bookings_active_slot_key;

CREATE UNIQUE INDEX idx_bookings_active_slot_key
ON bookings (slot_key)
WHERE status IN ('confirmed', 'checked_in');

ALTER TABLE bookings
    DROP CONSTRAINT IF EXISTS bookings_no_overlapping_active_slots;

ALTER TABLE bookings
    ADD CONSTRAINT bookings_no_overlapping_active_slots
    EXCLUDE USING gist (
        workspace_id WITH =,
        slot_range WITH &&
    )
    WHERE (status IN ('confirmed', 'checked_in'));

/* -------------------------------------------------------------------------- */
/* 2) BOOKING HOLDS: short-lived locks captured before payment completion.    */
/* -------------------------------------------------------------------------- */

CREATE TABLE IF NOT EXISTS booking_holds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hold_token UUID NOT NULL UNIQUE,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    user_email VARCHAR(255) NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    slot_key TEXT NOT NULL,
    slot_range tstzrange,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    status VARCHAR(20) NOT NULL DEFAULT 'active', -- active, offered, consumed, released, expired
    consumed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE booking_holds
    ADD COLUMN IF NOT EXISTS slot_key TEXT;

ALTER TABLE booking_holds
    ADD COLUMN IF NOT EXISTS slot_range tstzrange;

CREATE OR REPLACE FUNCTION booking_holds_set_slot_fields()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.workspace_id IS NOT NULL AND NEW.start_time IS NOT NULL AND NEW.end_time IS NOT NULL THEN
        NEW.slot_key := CONCAT(NEW.workspace_id::text, ':', NEW.start_time::text, ':', NEW.end_time::text);
        NEW.slot_range := tstzrange(NEW.start_time, NEW.end_time, '[)');
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_booking_holds_set_slot_fields ON booking_holds;

CREATE TRIGGER trg_booking_holds_set_slot_fields
BEFORE INSERT OR UPDATE OF workspace_id, start_time, end_time
ON booking_holds
FOR EACH ROW
EXECUTE FUNCTION booking_holds_set_slot_fields();

UPDATE booking_holds
SET
    slot_key = CONCAT(workspace_id::text, ':', start_time::text, ':', end_time::text),
    slot_range = tstzrange(start_time, end_time, '[)')
WHERE workspace_id IS NOT NULL
  AND start_time IS NOT NULL
  AND end_time IS NOT NULL
  AND (slot_key IS NULL OR slot_range IS NULL);

CREATE INDEX IF NOT EXISTS idx_booking_holds_workspace_time
ON booking_holds (workspace_id, start_time, end_time);

CREATE INDEX IF NOT EXISTS idx_booking_holds_user_email
ON booking_holds (user_email);

DROP INDEX IF EXISTS idx_booking_holds_active_slot_key;

CREATE UNIQUE INDEX idx_booking_holds_active_slot_key
ON booking_holds (slot_key)
WHERE is_active = true;

ALTER TABLE booking_holds
    DROP CONSTRAINT IF EXISTS booking_holds_valid_time_range;

ALTER TABLE booking_holds
    ADD CONSTRAINT booking_holds_valid_time_range
    CHECK (end_time > start_time);

ALTER TABLE booking_holds
    DROP CONSTRAINT IF EXISTS booking_holds_no_overlapping_active_slots;

ALTER TABLE booking_holds
    ADD CONSTRAINT booking_holds_no_overlapping_active_slots
    EXCLUDE USING gist (
        workspace_id WITH =,
        slot_range WITH &&
    )
    WHERE (is_active = true);

-- Optional helper cleanup command (run in a scheduled job):
-- UPDATE booking_holds
-- SET is_active = false, status = 'expired'
-- WHERE is_active = true AND expires_at < NOW();
