-- Add concurrency-safe slot locks for booking confirmation
-- Run this in Supabase SQL Editor before deploying updated backend routes.

CREATE EXTENSION IF NOT EXISTS btree_gist;

-- 1) Add slot_key to bookings and enforce uniqueness for active bookings.
ALTER TABLE bookings
ADD COLUMN IF NOT EXISTS slot_key TEXT;

UPDATE bookings
SET slot_key = CONCAT(
    workspace_id::text,
    ':',
    start_time::text,
    ':',
    end_time::text
)
WHERE slot_key IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_bookings_active_slot_key
ON bookings (slot_key)
WHERE status IN ('confirmed', 'checked_in');

ALTER TABLE bookings
DROP CONSTRAINT IF EXISTS bookings_no_overlapping_active_slots;

ALTER TABLE bookings
ADD CONSTRAINT bookings_no_overlapping_active_slots
EXCLUDE USING gist (
    workspace_id WITH =,
    tstzrange(start_time, end_time, '[)') WITH &&
)
WHERE (status IN ('confirmed', 'checked_in'));

-- 2) Create booking_holds table for temporary pre-payment reservation.
CREATE TABLE IF NOT EXISTS booking_holds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hold_token UUID NOT NULL UNIQUE,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    user_email VARCHAR(255) NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    slot_key TEXT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    status VARCHAR(20) NOT NULL DEFAULT 'active', -- active, consumed, released, expired
    consumed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_booking_holds_workspace_time
ON booking_holds (workspace_id, start_time, end_time);

CREATE INDEX IF NOT EXISTS idx_booking_holds_user_email
ON booking_holds (user_email);

CREATE UNIQUE INDEX IF NOT EXISTS idx_booking_holds_active_slot_key
ON booking_holds (slot_key)
WHERE is_active = true;

ALTER TABLE booking_holds
DROP CONSTRAINT IF EXISTS booking_holds_valid_time_range;

ALTER TABLE booking_holds
ADD CONSTRAINT booking_holds_valid_time_range
CHECK (end_time > start_time);

ALTER TABLE booking_holds
DROP CONSTRAINT IF EXISTS booking_holds_no_overlapping_active_slots;

ALTER TABLE booking_holds
ADD CONSTRAINT booking_holds_no_overlapping_active_slots
EXCLUDE USING gist (
    workspace_id WITH =,
    tstzrange(start_time, end_time, '[)') WITH &&
)
WHERE (is_active = true);

-- Optional helper cleanup command (run in scheduled job):
-- UPDATE booking_holds
-- SET is_active = false, status = 'expired'
-- WHERE is_active = true AND expires_at < NOW();
