-- Waitlist and automated reallocation support for bookings
-- Run after migration-booking-holds-and-slot-locks.sql

CREATE TABLE IF NOT EXISTS booking_waitlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    slot_key TEXT NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    user_email VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending', -- pending, offered, claimed, cancelled, expired
    priority SMALLINT NOT NULL DEFAULT 0,
    notes TEXT,
    offer_hold_token UUID,
    offer_expires_at TIMESTAMP WITH TIME ZONE,
    claimed_booking_id BIGINT REFERENCES bookings(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE booking_waitlist
    ADD CONSTRAINT booking_waitlist_valid_time_range
    CHECK (end_time > start_time);

CREATE INDEX IF NOT EXISTS idx_booking_waitlist_workspace_time
ON booking_waitlist (workspace_id, start_time, end_time);

CREATE INDEX IF NOT EXISTS idx_booking_waitlist_slot_status_created
ON booking_waitlist (slot_key, status, priority, created_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_booking_waitlist_user_slot_active
ON booking_waitlist (slot_key, user_email)
WHERE status IN ('pending', 'offered');

CREATE TRIGGER update_booking_waitlist_updated_at
BEFORE UPDATE ON booking_waitlist
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
