-- Tracks sent email events to prevent duplicate deliveries
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS booking_email_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    event_type VARCHAR(50) NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE (booking_id, event_type)
);

CREATE INDEX IF NOT EXISTS idx_booking_email_events_booking_id
    ON booking_email_events (booking_id);

CREATE INDEX IF NOT EXISTS idx_booking_email_events_event_type
    ON booking_email_events (event_type);
